/* tslint:disable */
/* eslint-disable */
/**
 * 트렐로 클론 API
 * 트렐로 유사 서비스의 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';

/**
 * a structured representation of an account
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'fullName'?: string;
    /**
     * 
     * @type {Link}
     * @memberof AccountResponse
     */
    'profileImage'?: Link;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'updatedAt': string;
}

