/* tslint:disable */
/* eslint-disable */
/**
 * 트렐로 클론 API
 * 트렐로 유사 서비스의 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorErrorsInnerLinks } from './error-errors-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorErrorsInnerSource } from './error-errors-inner-source';

/**
 * A JSON:API-compliant error object.
 * @export
 * @interface ErrorErrorsInner
 */
export interface ErrorErrorsInner {
    /**
     * a unique identifier for this particular occurrence of the problem
     * @type {string}
     * @memberof ErrorErrorsInner
     */
    'id'?: string;
    /**
     * 
     * @type {ErrorErrorsInnerLinks}
     * @memberof ErrorErrorsInner
     */
    'links'?: ErrorErrorsInnerLinks | null;
    /**
     * the HTTP status code applicable to this problem
     * @type {number}
     * @memberof ErrorErrorsInner
     */
    'status': number;
    /**
     * an application-specific error code
     * @type {string}
     * @memberof ErrorErrorsInner
     */
    'code'?: string;
    /**
     * a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization
     * @type {string}
     * @memberof ErrorErrorsInner
     */
    'title': string;
    /**
     * a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized
     * @type {string}
     * @memberof ErrorErrorsInner
     */
    'detail'?: string;
    /**
     * 
     * @type {ErrorErrorsInnerSource}
     * @memberof ErrorErrorsInner
     */
    'source'?: ErrorErrorsInnerSource | null;
    /**
     * a JSON meta object with non-standard meta-information about the error
     * @type {object}
     * @memberof ErrorErrorsInner
     */
    'meta'?: object | null;
}

