/* tslint:disable */
/* eslint-disable */
/**
 * 트렐로 클론 API
 * 트렐로 유사 서비스의 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * contains references to the source of the error
 * @export
 * @interface ErrorErrorsInnerSource
 */
export interface ErrorErrorsInnerSource {
    /**
     * a JSON Pointer [RFC6901] to the associated entity in the request document
     * @type {string}
     * @memberof ErrorErrorsInnerSource
     */
    'pointer'?: string;
    /**
     * indicates which URI query parameter caused the error
     * @type {string}
     * @memberof ErrorErrorsInnerSource
     */
    'parameter'?: string;
}

