/* tslint:disable */
/* eslint-disable */
/**
 * 트렐로 클론 API
 * 트렐로 유사 서비스의 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';

/**
 * 
 * @export
 * @interface PutMeRequest
 */
export interface PutMeRequest {
    /**
     * 사용자 이름
     * @type {string}
     * @memberof PutMeRequest
     */
    'firstname'?: string;
    /**
     * 사용자 성
     * @type {string}
     * @memberof PutMeRequest
     */
    'lastname'?: string;
    /**
     * 
     * @type {Link}
     * @memberof PutMeRequest
     */
    'profileImage'?: Link;
}

