openapi: 3.0.3
info:
  title: Trello Clone API
  version: 1.0.0
paths: {}
components:
  responses:
    500Response:
      description: 500 Internal Server Error
      content:
        application/json:
          schema:
            $ref: '../schemas/Error.yaml#/components/schemas/Error'
          example:
            errors:
              - title: 500 Internal Server Error
                status: 500
                detail: Internal server error
                id: 'ef2692f4-3ca4-44d9-b70a-7cfd5d78d3a1'