/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.trelloclone.backend.adapter.in.web.api;

import com.trelloclone.backend.adapter.in.web.model.BoardResponse;
import com.trelloclone.backend.adapter.in.web.model.BoardsResponse;
import com.trelloclone.backend.adapter.in.web.model.CreateBoardRequest;
import com.trelloclone.backend.adapter.in.web.model.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Tag(name = "Board", description = "보드 관련 API")
public interface BoardApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /v1/boards : 내 보드 목록 조회
     * 로그인한 사용자의 모든 보드 목록을 조회합니다.
     *
     * @return 보드 목록 조회 성공 (status code 200)
     *         or Not authorized (status code 401)
     *         or 500 Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getBoards",
        summary = "내 보드 목록 조회",
        description = "로그인한 사용자의 모든 보드 목록을 조회합니다.",
        tags = { "Board" },
        responses = {
            @ApiResponse(responseCode = "200", description = "보드 목록 조회 성공", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoardsResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "500 Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2", scopes={ "read" })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/boards",
        produces = { "application/json" }
    )
    
    default ResponseEntity<?> getBoards(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v1/boards : 보드 생성
     * 보드를 생성합니다.
     *
     * @param createBoardRequest  (required)
     * @return 보드 생성 성공 (status code 201)
     *         or Bad Request (status code 400)
     *         or Not authorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Unprocessable Entity (status code 422)
     *         or 500 Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "postBoards",
        summary = "보드 생성",
        description = "보드를 생성합니다.",
        tags = { "Board" },
        responses = {
            @ApiResponse(responseCode = "201", description = "보드 생성 성공", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoardResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "500 Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2", scopes={ "write" })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/boards",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<?> postBoards(
        @Parameter(name = "CreateBoardRequest", description = "", required = true) @RequestBody CreateBoardRequest createBoardRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
