openapi: 3.0.3
info:
  title: Trello Clone API
  version: 1.0.0
paths: {}
components:
  schemas:
    BoardResponse:
      title: BoardResponse Object
      description: a structured representation of a board
      type: object
      required:
        - id
        - title
        - owner
        - isPublic
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          example: 6c4a6b54-30c9-11ed-a261-0242ac120002
        title:
          type: string
          example: My Board
        description:
          type: string
          example: This is my board
        isPublic:
          type: boolean
          example: false
        backgroundColor:
          type: string
          pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'
        owner:
          $ref: './BoardOwner.yaml#/components/schemas/BoardOwner'
        createdAt:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2022-03-01T00:00:00Z