openapi: 3.0.3
info:
  title: Trello Clone API
  version: 1.0.0
paths: {}
components:
  schemas:
    SignupRequest:
      title: Signup Request Object
      description: a structured representation of a signup
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
          example: jonedoe@example.com
        password:
          type: string
          format: password
          example: password
        firstname:
          type: string
          example: jone
        lastname:
          type: string
          example: John Doe