parameters:
  accountIdParam:
    name: accountId
    in: path
    required: true
    description: 계정 ID
    schema:
      $ref: './schemas.yaml#/schemas/AccountId'
      
  workspaceIdParam:
    name: workspaceId
    in: path
    required: true
    description: 작업공간 ID
    schema:
      $ref: './schemas.yaml#/schemas/WorkspaceId'
      
  boardIdParam:
    name: boardId
    in: path
    required: true
    description: 보드 ID
    schema:
      $ref: './schemas.yaml#/schemas/BoardId'
      
  listIdParam:
    name: listId
    in: path
    required: true
    description: 리스트 ID
    schema:
      $ref: './schemas.yaml#/schemas/ListId'
      
  cardIdParam:
    name: cardId
    in: path
    required: true
    description: 카드 ID
    schema:
      $ref: './schemas.yaml#/schemas/CardId'
      
  labelIdParam:
    name: labelId
    in: path
    required: true
    description: 라벨 ID
    schema:
      $ref: './schemas.yaml#/schemas/LabelId'
      
  commentIdParam:
    name: commentId
    in: path
    required: true
    description: 댓글 ID
    schema:
      $ref: './schemas.yaml#/schemas/CommentId'
      
  attachmentIdParam:
    name: attachmentId
    in: path
    required: true
    description: 첨부파일 ID
    schema:
      $ref: './schemas.yaml#/schemas/AttachmentId'
      
  checklistIdParam:
    name: checklistId
    in: path
    required: true
    description: 체크리스트 ID
    schema:
      $ref: './schemas.yaml#/schemas/ChecklistId'
      
  checklistItemIdParam:
    name: itemId
    in: path
    required: true
    description: 체크리스트 항목 ID
    schema:
      $ref: './schemas.yaml#/schemas/ChecklistItemId'
      
  memberIdParam:
    name: memberId
    in: path
    required: true
    description: 멤버 ID
    schema:
      $ref: './schemas.yaml#/schemas/AccountId'
      
  invitationIdParam:
    name: invitationId
    in: path
    required: true
    description: 초대 ID
    schema:
      $ref: './schemas.yaml#/schemas/WorkspaceId'
