spring:
  datasource:
    name: trello-clone
    url: jdbc:h2:mem:trello-clone;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      authorizationserver:
        client:
          trello-client:
            registration:
              client-id: "trello-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "${application.frontend-url}/authorized"
              post-logout-redirect-uris:
                - "${application.frontend-url}/logout"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"

            require-authorization-consent: false
            require-proof-key: true

application:
  base-url: http://localhost:8080
  frontend-url: http://localhost:3000

logging:
  level:
    org.springframework.security: trace