openapi: 3.0.3
info:
  title: 트렐로 클론 API
  description: 트렐로 유사 서비스의 API
  version: 1.0.0
  contact:
    name: dongwon.kwak
servers:
  - url: http://localhost:8080/v1
    description: 메인 API 서버

# 태그 정의
tags:
  - name: Auth
    description: 사용자 인증 관련 API
  - name: Account
    description: 사용자 계정 관련 API
  - name: Board
    description: 보드 관련 API
  - name: List
    description: 리스트 관련 API
  - name: Card
    description: 카드 관련 API
  - name: Label
    description: 라벨 관련 API
  - name: Attachment
    description: 첨부파일 관련 API
  - name: Comment
    description: 댓글 관련 API
  - name: Checklist
    description: 체크리스트 관련 API
  - name: ChecklistItem
    description: 체크리스트 항목 관련 API

# 보안 스키마 참조
components:
  securitySchemes:
    OAuth2:
      $ref: 'components/securitySchemes/OAuth2.yaml#/components/securitySchemes/OAuth2'

security: []

paths:
  /v1/account/me:
    $ref: 'paths/v1-accounts-me.yaml#/paths/~1v1~1accounts~1me'

  /v1/auth/signup:
    $ref: 'paths/v1-auth-signup.yaml#/paths/~1v1~1auth~1signup'