openapi: 3.0.3
info:
  title: Trello Clone API
  version: 1.0.0
paths:
  /v1/boards/{boardId}/members/{accountId}:
    parameters:
      - $ref: '../components/parameters/boardId.yaml#/components/parameters/boardId'
      - $ref: '../components/parameters/accountId.yaml#/components/parameters/accountId'
    get:
      summary: 보드 멤버 조회
      description: 보드에 속한 특정 멤버를 조회합니다.
      operationId: getBoardMember
      tags:
        - Board
      security:
        - OAuth2: ['read']
      responses:
        '200':
          description: 보드 멤버 조회 성공
          content:
            application/json:
              schema:
                $ref: '../components/schemas/BoardMember.yaml#/components/schemas/BoardMember'
        '401':
          $ref: '../components/responses/401Response.yaml#/components/responses/401Response'
        '403':
          $ref: '../components/responses/403Response.yaml#/components/responses/403Response'
        '404':
          $ref: '../components/responses/404Response.yaml#/components/responses/404Response'
        '500':
          $ref: '../components/responses/500Response.yaml#/components/responses/500Response'
    put:
      summary: 보드 멤버 정보 수정
      description: 보드에 속한 특정 멤버의 정보를 수정합니다.
      operationId: putBoardMember
      tags:
        - Board
      security:
        - OAuth2: ['write']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schemas/UpdateBoardMemberRequest.yaml#/components/schemas/UpdateBoardMemberRequest'
      responses:
        '200':
          description: 보드 멤버 정보 수정 성공
          content:
            application/json:
              schema:
                $ref: '../components/schemas/BoardMember.yaml#/components/schemas/BoardMember'
        '400':
          $ref: '../components/responses/400Response.yaml#/components/responses/400Response'
        '401':
          $ref: '../components/responses/401Response.yaml#/components/responses/401Response'
        '403':
          $ref: '../components/responses/403Response.yaml#/components/responses/403Response'
        '404':
          $ref: '../components/responses/404Response.yaml#/components/responses/404Response'
        '500':
          $ref: '../components/responses/500Response.yaml#/components/responses/500Response'
    delete:
      summary: 보드 멤버 삭제
      description: 보드에서 특정 멤버를 삭제합니다.
      operationId: deleteBoardMember
      tags:
        - Board
      security:
        - OAuth2: ['write']
      responses:
        '204':
          description: 보드 멤버 삭제 성공
        '401':
          $ref: '../components/responses/401Response.yaml#/components/responses/401Response'
        '403':
          $ref: '../components/responses/403Response.yaml#/components/responses/403Response'
        '404':
          $ref: '../components/responses/404Response.yaml#/components/responses/404Response'
        '500':
          $ref: '../components/responses/500Response.yaml#/components/responses/500Response'